# File: .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches: [ "main" ]   # Run workflow when code is pushed to main
  pull_request:
    branches: [ "main" ]   # Run workflow on PRs to main

jobs:
  build:
    runs-on: ubuntu-latest  # Use latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"   # You can change to your required version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
